baseURL = "https://peabrane.github.io/"
title = "Rudy Pei (裴彦儒)"
theme = "PaperMod"

hasCJKLanguage = true
enableEmoji = true
enableRobotsTXT = true

languageCode = "en"

[pagination]
  pagerSize = 10

[outputs]
  home = ["HTML", "RSS", "JSON"]

[permalinks]
  post = "/:section/:contentbasename/"

[taxonomies]
  tag = "tags"

[menu]
  [[menu.main]]
    name = "About"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "Projects"
    url = "/post/"
    weight = 2
  [[menu.main]]
    name = "Music"
    url = "/comps/"
    weight = 3
  [[menu.main]]
    name = "Poems"
    url = "/poems/"
    weight = 4
  [[menu.main]]
    name = "CV"
    url = "/cv/"
    weight = 5
  [[menu.main]]
    name = "Links"
    url = "/links/"
    weight = 6
  [[menu.main]]
    name = "Search"
    url = "/search/"
    weight = 7

[params]
  env = "production"
  author = "PeaBrane"
  description = "the personal webpage of Yan Ru Pei"
  defaultTheme = "dark"
  mainsections = ["post"]

  ShowReadingTime = true
  ShowWordCount = true
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true
  ShowToc = false

  images = ["/img/og.png"]

  [params.profileMode]
    enabled = true
    title = "Rudy Pei (裴彦儒)"
    imageUrl = "/profile_pic.jpg"
    imageTitle = "Rudy Pei"
    imageWidth = 200
    imageHeight = 200
    subtitle = "AI viber | brain + quantum computing | physicist\n\nPeaBrane = peabrain + p-brane"

    [[params.profileMode.buttons]]
      name = "Projects"
      url = "/post/"
    [[params.profileMode.buttons]]
      name = "Codes"
      url = "https://github.com/PeaBrane"

  [[params.socialIcons]]
    name = "email"
    url = "mailto:yanrpei@gmail.com"
  [[params.socialIcons]]
    name = "github"
    url = "https://github.com/PeaBrane"
  [[params.socialIcons]]
    name = "googlescholar"
    url = "https://scholar.google.com/citations?user=qXQ2nNwAAAAJ&hl=en"
  [[params.socialIcons]]
    name = "linkedin"
    url = "https://www.linkedin.com/in/rudy-pei-33a3a7137"
  [[params.socialIcons]]
    name = "x"
    url = "https://x.com/PeaBrane10"
  [[params.socialIcons]]
    name = "youtube"
    url = "https://www.youtube.com/channel/UCwhYKbiCw6UTYU3rg4wC4yA"
  [[params.socialIcons]]
    name = "stackoverflow"
    url = "https://stackexchange.com/users/9236381/peabrane"
  [[params.socialIcons]]
    name = "rss"
    url = "/index.xml"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    noClasses = false

[minify]
  disableXML = true
